config/routes.rb
LearnLayouts::Application.routes.draw do

  get "propertydisplay/index"
  get 'display_property', to: 'display_property#index'

  resource :home

   root 'home#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/display_property_controller.rb
class DisplayPropertyController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /layouts
  # GET /layouts.json
  def index
    @home = Home.all
  end




end

app/controllers/propertydisplay_controller.rb
class PropertydisplayController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/display_property_helper.rb
module DisplayPropertyHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/helpers/propertydisplay_helper.rb
module PropertydisplayHelper
end

app/views/display_property/index.html.erb
<h1>DisplayProperty#index</h1>
<p>Find me in app/views/display_property/index.html.erb</p>

app/views/home/index.html.erb
<div id="main">
  <h1>Learning Layouts</h1>



  <%= link_to 'Display Property', display_property_path %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Learning Layouts</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/propertydisplay/index.html.erb
<h1>Propertydisplay#index</h1>
<p>Find me in app/views/propertydisplay/index.html.erb</p>